In [1]:
import pandas as pd
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = sns.load_dataset("titanic")

print("Titanic dataset loaded successfully!")
display(df.head())

Titanic dataset loaded successfully!

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
features = ["pclass", "sex", "age", "sibsp", "parch", "fare"]

df_model = df[features + ["survived"]].copy()

df_model["age"] = df_model["age"].fillna(df_model["age"].median())

df_model["sex"] = df_model["sex"].map({
    "male": 0,
    "female": 1
})

df_model = df_model.dropna()

print("Data prepared successfully!")
display(df_model.head())

Data prepared successfully!

   pclass  sex   age  sibsp  parch     fare  survived
0       3    0  22.0      1      0   7.2500         0
1       1    1  38.0      1      0  71.2833         1
2       3    1  26.0      0      0   7.9250         1
3       1    1  35.0      1      0  53.1000         1
4       3    0  35.0      0      0   8.0500         0

In [4]:
X = df_model[features]
y = df_model["survived"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (891, 6)
y shape: (891,)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Train/Test split completed!")

Train/Test split completed!

In [6]:
model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model.fit(X_train, y_train)

print("Decision Tree model trained successfully!")

Decision Tree model trained successfully!

In [7]:
joblib.dump(model, "titanic_decision_tree_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [8]:
import os

print(os.listdir())

['.anaconda', '.android', '.antigravity', '.bash_history', '.claude', '.conda', '.continuum', '.copilot', '.eclipse', '.gemini', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.node_repl_history', '.p2', '.vscode', '.vscode-shared', 'anaconda3', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'CRT', 'Documents', 'Downloads', 'eclipse', 'eclipse-workspace', 'Favorites', 'interncircle_data_lab_setup.ipynb', 'InternCircle_Task1_Titanic_Data_Lab.ipynb.ipynb', 'InternCircle_Task2_Data_Visualization_Titanic.ipynb', 'InternCircle_Task3_Ecommerce_Sales_Analysis.xlsx', 'InternCircle_Task3_Ecommerce_Sales_Analysis.xlsx.ipynb', 'InternCircle_Task4_First_Machine_Learning_Classifier.ipynb', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{86dbb75d-0b64-11f0-adb3-5802059bd2c5}.TM.blf', 'NTUSER.DAT{86dbb75d-0b64-11f0-adb3-5802059bd2c5}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{86dbb75d-0b64-11f0-adb3-5802059bd2c5}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'titanic_decision_tree_model.pkl', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Videos']